# My stuff
alias ls='ls -G'
alias tags='ctags -R --languages=ruby'
alias gap='git add -p'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gd='git diff'
alias gitdiff='git log|grep commit|cut -d " " -f2|head -n 2|xargs -n 2 git diff -R'
alias gl='git pull'
alias gp='git push'
alias gpr='git pull --rebase && ctags -R --languages=ruby'
alias grep='grep --color'
alias grh='git reset --hard'
alias gst='git status'
alias sc='rails console'
alias ss='rails server'
alias rc='rails c'
alias st='git status'
alias vundle='vim +PluginInstall +qall'

