# My stuff
alias ls='ls -G'
alias gap='git add -p'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gd='git diff'
alias gpr='git pull --rebase'
alias grep='grep --color'
alias grh='git reset --hard'
alias gst='git status'
alias pwd_name='basename $PWD'
alias gprm='git co master && git pull --rebase && git co - && git rebase master'
alias vox='docker compose --project-directory $WORK_DIR/$WORK_DOCKER_COMPOSE_DIR/'
