# My stuff
alias ls='ls -G'
alias tags='ctags -R --languages=ruby'
alias gap='git add -p'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gd='git diff'
alias gpr='git pull --rebase && ctags -R'
alias grep='grep --color'
alias grh='git reset --hard'
alias gst='git status'
alias vundle='vim +PluginInstall +qall'
alias pwd_name='basename $PWD'
alias gprm='git co master && git pull --rebase && git co - && git rebase master'
alias vox='docker compose --project-directory ~/Repositories/VoApps/vo-compose/'
