cursor #fbf1c7
cursor_text_color #ebdbb2

foreground            #fbf1c7
background            #1c1c1c
selection_foreground  #1c1c1c
selection_background  #b16286
url_color             #83a598

color0   #1c1c1c
color1   #bd7655
color2   #52a556
color3   #cec45c
color4   #759c8d
color5   #2f4c41
color6   #83a598
color7   #a2ada9
color8   #767e7b
color9   #dea58b
color10  #80c683
color11  #f7efa0
color12  #95b5a9
color13  #b7d6ca
color14  #d1e7de
color15  #e9efec
